### ISSUE TITLE
Invited talk links should be 2018-helsinki instead of 2018

### ISSUE THREAD

**Issue by SteveBronder** [stan-dev/stancon_talks#10]
Slide links go to
https://github.com/stan-dev/stancon_talks/blob/master/2018/Invited-Talks/lieu.pdf
but should go to
https://github.com/stan-dev/stancon_talks/blob/master/2018-helsinki/Invited-Talks/lieu.pdf

**Comment by lauken13** [comment]
Missed that! Have updated and tested all links.

Lauren

**Comment by SteveBronder** [comment]
ty!
